name: vento
description: A wrapper package for data and api handling in Flutter built on top of flutter_bloc and freezed package.
version: 0.0.1
author: Ashish Rawat
homepage: https://github.com/ashishrawat2911/vento

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: 0.14.1
  cupertino_icons: ^1.0.0
  flutter_bloc: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.11.1
  freezed: 0.12.7

flutter:
